version: '3.9'
services:
  nginx_mercadona:
    image: nginx:latest
    container_name: nginx_$PROJECT_NAME
    ports:
      - "$NGINX_PORT:80"
    volumes:
      - ../:/code
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mercadona
  php_mercadona:
    build: ./php
    container_name: php_$PROJECT_NAME
    environment:
      XDEBUG_CONFIG: remote_host={{YOUR_IP_ADDRESS}}
    volumes:
      - ../:/code
      - ./php:/usr/local/etc/php
    networks:
      - mercadona
  mysql_mercadona:
    image: mysql:8.0
    container_name: mysql_$PROJECT_NAME
    restart: unless-stopped
    tty: true
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "$MYSQL_PORT:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
    volumes:
      - './db/data:/var/lib/mysql'
      - './db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './db/sql:/docker-entrypoint-initdb.d'
    networks:
      - mercadona
networks:
  mercadona:
    driver: bridge