version: '3.9'
services:
  nginx_mercadona:
    image: nginx:latest
    container_name: nginx_$PROJECT_NAME
    ports:
      - "$NGINX_PORT:80"
    volumes:
      - ../:/code
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mercadona
  php_mercadona:
    build: ./php
    container_name: php_$PROJECT_NAME
    volumes:
      - ../:/code
      - ./php:/usr/local/etc/php
    networks:
      - mercadona
    depends_on:
      - mysql_mercadona
  mysql_mercadona:
    image: mysql:8.0
    container_name: mysql_$PROJECT_NAME
    ports:
      - "$MYSQL_PORT:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
    networks:
      - mercadona
networks:
  mercadona:
    driver: bridge  