services:
  nginx_mercadona:
    image: nginx:latest
    container_name: nginx_$PROJECT_NAME
    ports:
      - "$NGINX_PORT:80"
    expose:
      - "$NGINX_PORT"
    volumes:
      - ../:/code
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      mercadona:
        ipv4_address: 10.5.0.5
  php_mercadona:
    build: ./php
    container_name: php_$PROJECT_NAME
    volumes:
      - ../:/code
      - ./php:/usr/local/etc/php
    ports:
      - "$PHP_PORT:9000"
    expose:
      - "$PHP_PORT"
    networks:
      mercadona:
        ipv4_address: 10.5.0.7
    depends_on:
      - mysql_mercadona
  mysql_mercadona:
    image : mariadb:latest
    container_name: mysql_$PROJECT_NAME
    command: --default-authentication-plugin=mysql_native_password && mysqladmin -u root -p status
    restart: always
    ports:
      - "$MYSQL_PORT:3306"
    expose:
      - "$MYSQL_PORT"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_TCP_PORT:${MYSQL_PORT}
    networks:
      mercadona:
        ipv4_address: 10.5.0.6
networks:
  mercadona:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1